#!/bin/bash -x
set -e
HOME_DIR=/home/debian/
echo $PATH
git clone git@github.com:trilioData/automation.git
cd $(pwd)/automation/debian_scripts
export BASE_DIR=$(pwd)
export VERSION="$TVAULT_VERSION"
mkdir -p /var/www/html/deb-repo/deb-repo/
REPO_DIR=/var/www/html/deb-repo/deb-repo/
WEB_HOST_PATH=/var/www/html
cd $BASE_DIR
echo ${BASE_DIR}

#cp -rf ${BASE_DIR}/automation/debian_scripts/* .

#build tvault-horizon-pluigin packages
git clone git@github.com:trilioData/horizon-tvault-plugin.git
${BASE_DIR}/build_deb.sh tvault-horizon-plugin ${VERSION}

#build python-workloadmanger packages
git clone git@github.com:trilioData/workloadmanager-client.git
${BASE_DIR}/build_deb.sh python-workloadmgrclient ${VERSION}

#build contego-api debian packages
git clone git@github.com:trilioData/contego.git
${BASE_DIR}/build_deb.sh tvault-contego-api ${VERSION}

#build contego debian pacakges
${BASE_DIR}/build_deb.sh tvault-contego ${VERSION}

#cp ${BASE_DIR}/automation/openstack-build-scripts/artifacts/newton/tvault-contego-virtenv.tar.gz ${BASE_DIR}/contego_extension/
cp ${BASE_DIR}/../openstack-build-scripts/artifacts/queens/tvault-contego-virtenv.tar.gz ${BASE_DIR}/contego_extension/

#build contego-extension debian package
${BASE_DIR}/build_deb.sh contego ${VERSION}
mv ${BASE_DIR}/contego_${VERSION}_amd64.deb ${BASE_DIR}/tvault-contego-extension_${VERSION}_all.deb

#build dmapi debian package
git clone git@github.com:trilioData/dmapi.git  
${BASE_DIR}/build_deb.sh dmapi ${VERSION}

#move debian packages to tvault_debain_pacakges
mkdir -p ${BASE_DIR}/tvault_debian_packages_${VERSION}
mv ${BASE_DIR}/*.deb ${REPO_DIR}

cd ${WEB_HOST_PATH}
dpkg-scanpackages deb-repo /dev/null | gzip -9c > deb-repo/Packages.gz
cd ${BASE_DIR}

#remove other files generated by build contego packages
rm -rf contego_${VERSION}*
